export const REQUEST_NEWS_API = "REQUEST_NEWS_API";
export const FAILURE_NEWS_API = "FAILURE_NEWS_API";
export const SUCCESS_NEWS_API = "SUCCESS_NEWS_API";
export const VOTE_INCREMENT = "VOTE_INCREMENT";
export const REMOVE_NEWS = "REMOVE_NEWS";



